[tool.poetry]
name = "whisper_dictate"
version = "0.2.0"
description = "Dictate using whisper and type so you don't have to."
authors = ["Alan Descoins <alan@tryolabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
pynput = "^1.7.7"
pyperclip = "^1.8.2"
openai = "^1.33.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
black = "^24.4.2"
isort = "^5.13.2"

[tool.black]
line-length = 100
preview = true

[tool.isort]
atomic = true
profile = "black"

[tool.poetry.scripts]
wdic = "whisper_dictate.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
